### ISSUE TITLE
[10] Integrate global asset database to data-lake & Databricks

### ISSUE THREAD

**Issue by RamziAssaf** [RamziAssaf/Bison-new-data-board#1]
**Latest update:**
- It seems that the global asset database has been deployed to PROD with real data.
- Should encompass unique naming & IDs of Companies, Wells, Disposals (Both new global docs and edits to existing children)
- Ingestion and infra are now controlled within the data-lake repo

**Work needed:**
- Integrate the global asset database to the data lake & Databricks

**Tasks:**
- [x] (Priority: HIGH) Ingest New Docs (https://github.com/circle9r/dbx-notebooks/issues/486)
- [ ] (Priority: MED) Populate Global Assets from Canonical Sources (https://github.com/circle9r/dbx-notebooks/issues/495)
- [ ] (Priority: MED) Research Cluster Analytics to Derive Multiple Instances of Same Company (https://github.com/circle9r/dbx-notebooks/issues/506)
- [ ] (Priority: LOW) Integrate Match Analytics to Labrador Persistence (https://github.com/circle9r/labrador/issues/85)
- [ ] (Priority: LOW) Make Match Candidates Available in Labrador (https://github.com/circle9r/dbx-notebooks/issues/494)
