### ISSUE TITLE
[10] Integrate GitHub API into Data Lake

### ISSUE THREAD

**Issue by RamziAssaf** [RamziAssaf/Bison-new-data-board#15]
**Task description:**
- We would like to be able to ingest aspects of the GitHub API and make it available within the Data Lake for general use. 

**Sub-tasks**:
- [ ] Set Up Access to GitHub API (TBD)
- [ ] Build Data Lake Ingestion (TBD)
- [ ] Build Small Demo Metrics (TBD)
- [ ] Build Demo PowerBI Metrics (TBD)

**Advanced Productivity Analytics this would allow**:
* Continuous Velocity Measurement
* Advanced Graphics Analytics
* Custom Multi-Team Dashboard
* Larger Scale Multi-Team/Multi-Repo Initiative Tracking (e.g. Uniform Milestones)
* PR & Rework Metrics
* Secondary Integrations/Possible Refinements Outside of GitHub Actions Scope
