### ISSUE TITLE
[10] Integrate Aries to PowerBI

### ISSUE THREAD

**Issue by RamziAssaf** [RamziAssaf/Bison-new-data-board#22]
**About Aries:**
- Aries is an industry software used for volume projections
- It’s just an Access database. It's an old-fashioned software that uses a bit lock as their licensing device, so logging in is not an option, nor is it necessary.

**Context:**
- On Oct 2020, we rolled our type curve forecasting into Aries.
- Brian Babb is the owner of Aries and is responsible for updating data each month once we have the data from operators.
- PowerBI would be a great tool for our actual vs. forecast comparisons. 
- Point of contact: Brian Babb & Ryan Fisher (former employee).

**General Task:**
- Integrate Aries <-> PowerBI bi-directionally
- I.e. Get data from Aries into PowerBI Reports + Send data from PowerBI to Aries

**Solution:**
- It may make sense to have Databricks handle the bi-directional integration of Aries <-> PowerBI. 
- We could use a SharePoint location to pass the Access db file back & forth and present the Access tables in the data lake for PowerBI.

**Database copy & Tables descriptions:**
- Database copy is attached. 
- Table AC_PROPERTY: contains the master identification information
- Table AC_DAILY: where we store the daily water volumes
- Table AC_PRODUCT: where monthly volumes are stored

From Brian Babb:
- We are indifferent as to which table, or both, are populated. 
- If a customer only supplies monthly volumes, then we want it in AC_PRODUCT. 
- If they supply daily volumes, then we want it loaded to AC_DAILY. 
- Adding up the daily volumes and also storing the sum as a monthly volume in AC_PRODUCT is good, but not necessary.

- Should be simple to load, however the difficulty is matching the meter/well source information to my Aries case information, which appears to be a hybrid created by former employee Ryan Fisher.
- I may need to change my Aries case designations to better match the meter/well source data.

**Tasks:**

- [ ] Integrate daily volume confirmed by operator into Aries 
_(This will eliminate the need for someone to create a data upload file for Aries)_
- [ ] Integrate Aries into PowerBI
- [ ] Type curve forecast vs. actual workspace in PowerBI. 
_(This should include the following data that users can click through: By BWM entity, By Operator, By Contract, By Well, By area)_
