### ISSUE TITLE
[3] Add projections to the Business Health dashboard reports

### ISSUE THREAD

**Issue by RamziAssaf** [RamziAssaf/Bison-new-data-board#23]
**Tasks:**
- [ ] Finance (Will Smith?) to provide an Excel file with the business projection information needed for the Business Health dashboard reports
- [ ] Data team to ingest this Excel file (into Aries?)
- [ ] BI team to generate the business projections into the Business Health Dashboard reports on PowerBI

---------

**From previous ticket:**

Currently awaiting sample file from Finance

In order to layer business projections into the Business Health Dashboard Reports, we will need to ingest that information, provided to us in an excel file from Finance. Bekah will get a sample file from Will Smith, then Ellisor can begin to build the ingestion so Christina has that data available for the PowerBI reports.

It may make more sense for us to get Aries integration going since that seems to be where the projections come from, but I can get more clarity on that from Will Smith & Brian Babb.
