### ISSUE TITLE
[5] Migrate all source views from Mongo data to TSQ method

### ISSUE THREAD

**Issue by RamziAssaf** [RamziAssaf/Bison-new-data-board#29]
_All instances of deployment will require a full backload to update the TSQ field for new computation approach_

**Tasks**:
- [ ] gopher: Update TSQ computation, migrate all views (TBD)
- [ ] chickfila: Update TSQ computation, migrate all views (TBD)
- [ ] platypus: Update TSQ computation, migrate all views (TBD)
- [ ] platypus: migrate views (with backload) only (TBD, likely should break up around checkpoint interaction)
