### ISSUE TITLE
[5] Improve PowerBI dashboards

### ISSUE THREAD

**Issue by RamziAssaf** [RamziAssaf/Bison-new-data-board#3]
**Tasks:**
- [ ] Log dates for customer files
- [ ] Improve PowerBI adoption (increase UI trust, do training workshops with business, etc.)

**More tasks - Views to Evaluate:**
- [ ] bi_views. total_daily_plow_ upstream_volume_by_disposal
- [ ] bi_views. total_daily_volume_ by_disposal
- [ ] bi_views. total_daily_volume_ by_operator_disposal
- [ ] bi_views. total_daily_plow_upstream_volume _by_meter_operator_disposal
- [ ] bi_views.summaryticket_audit
- [ ] bi_views. disposal_prev_day_ consolidated_volume_report
- [ ] bi_views. disposal_prev_day_ consolidated_volume_report_formatted
